using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class cameracontroller : MonoBehaviour
{

    public Transform personaje; 
    private float tama単oCamara;
    private float alturaPantalla;

    // Start is called before the first frame update
    void Start()
    {
        tama単oCamara = Camera.main.orthographicSize;
        alturaPantalla = tama単oCamara*2;
    }

    // Update is called once per frame
    void Update()
    {
      calcularPosicionCamara();  
    }

    void calcularPosicionCamara()
    {
        int pantallaPersonaje = (int) (personaje.position.x / alturaPantalla);
        float alturaCamara = (pantallaPersonaje + alturaPantalla) + tama単oCamara;
        Transform.position = new vector3(Transform.position.x, alturaCamara, Transform.position.z);
    }
}
